[toe]
base_dir = "/opt/matrix/var/cache/toe"
log_file = "/opt/matrix/var/logs/toe/log.log"
pid_file = "/opt/matrix/sysinfo/toe.pid"
max_message_size = 65536 # default 64KB
servers = ["nats://user:user@10.10.27.20:4222"]

[PayloadEncoder]
append_newlines = false

[split_n]
type = "TokenSplitter"

# job
[JobInput]
type = "JobInput"
# keyspaces = []

[JobOutput]
type = "JobOutput"
#encoding = "gbk"
master = "hdim"
message_matcher = "Logger == 'JobInput'"
encoder = "PayloadEncoder"
# keyspaces = []
# call_data

###############################测试click的相关demo#################################################
[ClickDataInput]
type = "LogstreamerInput"
log_directory = "/opt/tools/tmp"
file_match = '(?P<FileName>[^/]+).cvs'
differentiator = ["FileName"]

[ClickDataOutput]
type = "NatsOutput"
is_streaming = true
subject = "matrix.rules.click"
reconnect = true
message_matcher = "Logger == 'ClickDataInput'"
encoder = "PayloadEncoder"
use_buffering = false
use_protocol = true

[ClickDataOutput.attr]

[ClickDataOutput.buffering]
max_file_size = 1048576  #1MB
max_buffer_size = 10485760  #10MB
full_action = "drop"
cursor_update_count = 100

#################################测试插入base_user表的相关数据###############################################
[BaseUserDataInput]
type = "LogstreamerInput"
log_directory = "/opt/tools/baseuser"
file_match = '(?P<FileName>[^/]+).csv'
differentiator = ["FileName"]

[BaseUserDataOutput]
type = "NatsOutput"
is_streaming = true
subject = "hdim.rules.userrecord"
reconnect = true
message_matcher = "Logger == 'BaseUserDataInput'"
encoder = "PayloadEncoder"
use_buffering = false
use_protocol = true

[BaseUserDataOutput.attr]

[BaseUserDataOutput.buffering]
max_file_size = 1048576  #1MB
max_buffer_size = 10485760  #10MB
full_action = "drop"
cursor_update_count = 100


##############################配置关系的相关测试demo   ##################################################
[GxDataInput]
type = "LogstreamerInput"
log_directory = "/opt/tools/gx"
file_match = '(?P<FileName>[^/]+).csv'
differentiator = ["FileName"]

[GxDataOutput]
type = "NatsOutput"
is_streaming = true
subject = "hdim.rules.gx"
reconnect = true
message_matcher = "Logger == 'GxDataInput'"
encoder = "PayloadEncoder"
use_buffering = false
use_protocol = true

[GxDataOutput.attr]

[GxDataOutput.buffering]
max_file_size = 1048576  #1MB
max_buffer_size = 10485760  #10MB
full_action = "drop"
cursor_update_count = 100
 
 
 
##################################AlipayDealRecord   支付宝交易记录csv##############################################
[AlipayDealRecordDataInput]
type = "LogstreamerInput"
log_directory = "/opt/tools/AlipayDealRecord"
file_match = '(?P<FileName>[^/]+).csv'
differentiator = ["FileName"]

[AlipayDealRecordDataOutput]
type = "NatsOutput"
is_streaming = true   
subject = "hdim.rules.alipaydealrecord_relus"
reconnect = true
message_matcher = "Logger == 'AlipayDealRecordDataInput'"
encoder = "PayloadEncoder"
use_buffering = false
use_protocol = true 

[AlipayDealRecordDataOutput.attr]

[AlipayDealRecordDataOutput.buffering]
max_file_size = 1048576  #1MB
max_buffer_size = 10485760  #10MB
full_action = "drop"
cursor_update_count = 100

##################################AlipayRegisterInfo   支付宝注册信息csv##############################################
[AlipayRegisterInfoDataInput]
type = "LogstreamerInput"
log_directory = "/opt/tools/AlipayRegisterInfo"
file_match = '(?P<FileName>[^/]+).csv'
differentiator = ["FileName"]

[AlipayRegisterInfoDataOutput]
type = "NatsOutput"
is_streaming = true
subject = "hdim.rules.alipayregisterinfo_rules"
reconnect = true
message_matcher = "Logger == 'AlipayRegisterInfoDataInput'"
encoder = "PayloadEncoder"
use_buffering = false
use_protocol = true 

[AlipayRegisterInfoDataOutput.attr]

[AlipayRegisterInfoDataOutput.buffering]
max_file_size = 1048576  #1MB
max_buffer_size = 10485760  #10MB
full_action = "drop"
cursor_update_count = 100


###################################AlipayAccoutDetails   支付宝账户明细csv#############################################
[AlipayAccoutDetailsDataInput]
type = "LogstreamerInput"   
log_directory = "/opt/tools/AlipayAccoutDetails"
file_match = '(?P<FileName>[^/]+).csv'
differentiator = ["FileName"]

[AlipayAccoutDetailsDataOutput]
type = "NatsOutput"
is_streaming = true
subject = "hdim.rules.alipayaccoutdetails_relus"
reconnect = true
message_matcher = "Logger == 'AlipayAccoutDetailsDataInput'"
encoder = "PayloadEncoder"
use_buffering = false
use_protocol = true 

[AlipayAccoutDetailsDataOutput.attr]

[AlipayAccoutDetailsDataOutput.buffering]
max_file_size = 1048576  #1MB
max_buffer_size = 10485760  #10MB
full_action = "drop"
cursor_update_count = 100


#################################AliPayTransferDetails   支付宝转账明细csv###############################################
[AliPayTransferDetailsDataInput]
type = "LogstreamerInput"   
log_directory = "/opt/tools/AlipayTransferDetails"
file_match = '(?P<FileName>[^/]+).csv'
differentiator = ["FileName"]

[AliPayTransferDetailsDataOutput]
type = "NatsOutput"
is_streaming = true
subject = "hdim.rules.alipaytransferdetails_rules"
reconnect = true
message_matcher = "Logger == 'AliPayTransferDetailsDataInput'"
encoder = "PayloadEncoder"
use_buffering = false
use_protocol = true 

[AliPayTransferDetailsDataOutput.attr]

[AliPayTransferDetailsDataOutput.buffering]
max_file_size = 1048576  #1MB
max_buffer_size = 10485760  #10MB
full_action = "drop"
cursor_update_count = 100


##############################CallLog  通话记录csv##################################################
[CallLogDataInput]
type = "LogstreamerInput"   
log_directory = "/opt/tools/CallLog1"
file_match = '(?P<FileName>[^/]+).csv'
#differentiator = ["FileName"]
priority = ["FileName"]

[CallLogDataOutput]
type = "NatsOutput"
is_streaming = true
subject = "hdim.rules.skipcall_rules"
#subject = "hdim.rules.calllog_rules"
reconnect = true
message_matcher = "Logger == 'CallLogDataInput'"
encoder = "PayloadEncoder"
use_buffering = false
use_protocol = true 

[CallLogDataOutput.attr]

[CallLogDataOutput.buffering]
max_file_size = 1048576  #1MB
max_buffer_size = 10485760  #10MB
full_action = "drop"
cursor_update_count = 100

###############################Express  快递记录csv#################################################
[ExpressDataInput]
type = "LogstreamerInput"   
log_directory = "/opt/tools/Express"
file_match = '(?P<FileName>[^/]+).csv'
differentiator = ["FileName"]

[ExpressDataOutput]
type = "NatsOutput"
is_streaming = true
subject = "hdim.rules.express_rules"
reconnect = true
message_matcher = "Logger == 'ExpressDataInput'"
encoder = "PayloadEncoder"
use_buffering = false
use_protocol = true 

[ExpressDataOutput.attr]

[ExpressDataOutput.buffering]
max_file_size = 1048576  #1MB
max_buffer_size = 10485760  #10MB
full_action = "drop"
cursor_update_count = 100


###############################GotoCar  出行记录csv#################################################
[GotoCarDataInput]
type = "LogstreamerInput"   
log_directory = "/opt/tools/GotoCar"
file_match = '(?P<FileName>[^/]+).csv'
differentiator = ["FileName"]

[GotoCarDataOutput]
type = "NatsOutput"
is_streaming = true
subject = "hdim.rules.gotocar_rules"
reconnect = true
message_matcher = "Logger == 'GotoCarDataInput'"
encoder = "PayloadEncoder"
use_buffering = false
use_protocol = true 

[GotoCarDataOutput.attr]

[GotoCarDataOutput.buffering]
max_file_size = 1048576  #1MB
max_buffer_size = 10485760  #10MB
full_action = "drop"
cursor_update_count = 100

###############################GotoMinhangExit  民航离岗csv#################################################
[GotoMinhangExitDataInput]
type = "LogstreamerInput"   
log_directory = "/opt/tools/GotoMinhangExit"
file_match = '(?P<FileName>[^/]+).csv'
differentiator = ["FileName"]

[GotoMinhangExitDataOutput]
type = "NatsOutput"
is_streaming = true 
subject = "hdim.rules.gotominhangexit_rules"
reconnect = true
message_matcher = "Logger == 'GotoMinhangExitDataInput'"
encoder = "PayloadEncoder"
use_buffering = false
use_protocol = true 

[GotoMinhangExitDataOutput.attr]

[GotoMinhangExitDataOutput.buffering]
max_file_size = 1048576  #1MB
max_buffer_size = 10485760  #10MB
full_action = "drop"
cursor_update_count = 100


###############################GotoMinhangTicket  全国民航订票数据csv#################################################
[GotoMinhangTicketDataInput]
type = "LogstreamerInput"   
log_directory = "/opt/tools/GotoMinhangTicket"
file_match = '(?P<FileName>[^/]+).csv'
differentiator = ["FileName"]

[GotoMinhangTicketDataOutput]
type = "NatsOutput"
is_streaming = true 
subject = "hdim.rules.gotominhangticket_rules"
reconnect = true
message_matcher = "Logger == 'GotoMinhangTicketDataInput'"
encoder = "PayloadEncoder"
use_buffering = false
use_protocol = true 

[GotoMinhangTicketDataOutput.attr]

[GotoMinhangTicketDataOutput.buffering]
max_file_size = 1048576  #1MB
max_buffer_size = 10485760  #10MB
full_action = "drop"
cursor_update_count = 100


###############################GotoOutin  出入境csv#################################################
[GotoOutinDataInput]
type = "LogstreamerInput"   
log_directory = "/opt/tools/GotoOutin"
file_match = '(?P<FileName>[^/]+).csv'
differentiator = ["FileName"]

[GotoOutinDataOutput]
type = "NatsOutput"
is_streaming = true 
subject = "hdim.rules.gotooutin_rules"
reconnect = true
message_matcher = "Logger == 'GotoOutinDataInput'"
encoder = "PayloadEncoder"
use_buffering = false
use_protocol = true 

[GotoOutinDataOutput.attr]

[GotoOutinDataOutput.buffering]
max_file_size = 1048576  #1MB
max_buffer_size = 10485760  #10MB
full_action = "drop"
cursor_update_count = 100



###############################Hotel  住宿数据csv#################################################
[HotelDataInput]
type = "LogstreamerInput"   
log_directory = "/opt/tools/Hotel"
file_match = '(?P<FileName>[^/]+).csv'
differentiator = ["FileName"]

[HotelDataOutput]
type = "NatsOutput"
is_streaming = true 
subject = "hdim.rules.hotel_rules"
reconnect = true
message_matcher = "Logger == 'HotelDataInput'"
encoder = "PayloadEncoder"
use_buffering = false
use_protocol = true 

[HotelDataOutput.attr]

[HotelDataOutput.buffering]
max_file_size = 1048576  #1MB
max_buffer_size = 10485760  #10MB
full_action = "drop"
cursor_update_count = 100


###############################Phone  手机号csv#################################################
[PhoneDataInput]
type = "LogstreamerInput"   
log_directory = "/opt/tools/Phone"
file_match = '(?P<FileName>[^/]+).csv'
differentiator = ["FileName"]

[PhoneDataOutput]
type = "NatsOutput"
is_streaming = true 
subject = "hdim.rules.phone_rules"
reconnect = true
message_matcher = "Logger == 'PhoneDataInput'"
encoder = "PayloadEncoder"
use_buffering = false
use_protocol = true 

[PhoneDataOutput.attr]

[PhoneDataOutput.buffering]
max_file_size = 1048576  #1MB
max_buffer_size = 10485760  #10MB
full_action = "drop"
cursor_update_count = 100


###############################UnionpayAccount  银联账号csv#################################################
[UnionpayAccountDataInput]
type = "LogstreamerInput"   
log_directory = "/opt/tools/UnionpayAccount"
file_match = '(?P<FileName>[^/]+).csv'
differentiator = ["FileName"]

[UnionpayAccountDataOutput]
type = "NatsOutput"
is_streaming = true 
subject = "hdim.rules.unionpayaccount_rules"
reconnect = true
message_matcher = "Logger == 'UnionpayAccountDataInput'"
encoder = "PayloadEncoder"
use_buffering = false
use_protocol = true 

[UnionpayAccountDataOutput.attr]

[UnionpayAccountDataOutput.buffering]
max_file_size = 1048576  #1MB
max_buffer_size = 10485760  #10MB
full_action = "drop"
cursor_update_count = 100



###############################UnionpayTrans  银联交易数据csv#################################################
[UnionpayTransDataInput]
type = "LogstreamerInput"   
log_directory = "/opt/tools/UnionpayTrans"
file_match = '(?P<FileName>[^/]+).csv'
differentiator = ["FileName"]

[UnionpayTransDataOutput]
type = "NatsOutput"
is_streaming = true 
subject = "hdim.rules.unionpaytrans_rules"
reconnect = true
message_matcher = "Logger == 'UnionpayTransDataInput'"
encoder = "PayloadEncoder"
use_buffering = false
use_protocol = true 

[UnionpayTransDataOutput.attr]

[UnionpayTransDataOutput.buffering]
max_file_size = 1048576  #1MB
max_buffer_size = 10485760  #10MB
full_action = "drop"
cursor_update_count = 100


###############################WeChatBank   微信绑定银行卡数据csv#################################################
[WeChatBankDataInput]
type = "LogstreamerInput"   
log_directory = "/opt/tools/WeChatBank"
file_match = '(?P<FileName>[^/]+).csv'
differentiator = ["FileName"]

[WeChatBankDataOutput]
type = "NatsOutput"
is_streaming = true 
subject = "hdim.rules.wechatbank_rules"
reconnect = true
message_matcher = "Logger == 'WeChatBankDataInput'"
encoder = "PayloadEncoder"
use_buffering = false
use_protocol = true 

[WeChatBankDataOutput.attr]

[WeChatBankDataOutput.buffering]
max_file_size = 1048576  #1MB
max_buffer_size = 10485760  #10MB
full_action = "drop"
cursor_update_count = 100



###############################WeChatTransdata  微信交易数据csv#################################################
[WeChatTransdataDataInput]
type = "LogstreamerInput"   
log_directory = "/opt/tools/WeChatTransdata"
file_match = '(?P<FileName>[^/]+).csv'
differentiator = ["FileName"]

[WeChatTransdataDataOutput]
type = "NatsOutput"
is_streaming = true 
subject = "hdim.rules.wechattransdata_rules"
reconnect = true
message_matcher = "Logger == 'WeChatTransdataDataInput'"
encoder = "PayloadEncoder"
use_buffering = false
use_protocol = true 

[WeChatTransdataDataOutput.attr]

[WeChatTransdataDataOutput.buffering]
max_file_size = 1048576  #1MB
max_buffer_size = 10485760  #10MB
full_action = "drop"
cursor_update_count = 100


#################################GotoRail  铁路出行的相关记录 ###############################################
[GotoRailDataInput]
type = "LogstreamerInput"
log_directory = "/opt/tools/GotoRail"
file_match = '(?P<FileName>[^/]+).csv'
differentiator = ["FileName"]

[GotoRailDataOutput]
type = "NatsOutput"
is_streaming = true
subject = "hdim.rules.gotorail_rules"
reconnect = true
message_matcher = "Logger == 'GotoRailDataInput'"
encoder = "PayloadEncoder"
use_buffering = false
use_protocol = true

[GotoRailDataOutput.attr]

[GotoRailDataOutput.buffering]
max_file_size = 1048576  #1MB
max_buffer_size = 10485760  #10MB
full_action = "drop"
cursor_update_count = 100

#################################CarStart  汽车出行的相关记录 ###############################################
[CarStartDataInput]
type = "LogstreamerInput"
log_directory = "/opt/tools/CarStart"
file_match = '(?P<FileName>[^/]+).csv'
differentiator = ["FileName"]

[CarStartDataOutput]
type = "NatsOutput"
is_streaming = true
subject = "hdim.rules.carstart_rules"
reconnect = true
message_matcher = "Logger == 'CarStartDataInput'"
encoder = "PayloadEncoder"
use_buffering = false
use_protocol = true

[CarStartDataOutput.attr]

[CarStartDataOutput.buffering]
max_file_size = 1048576  #1MB
max_buffer_size = 10485760  #10MB
full_action = "drop"
cursor_update_count = 100


##################################PerBasisInfo   人员列表csv##############################################
[PerBasisInfoDataInput]
type = "LogstreamerInput"
log_directory = "/opt/tools/PerBasisInfo"
file_match = '(?P<FileName>[^/]+).csv'
differentiator = ["FileName"]

[PerBasisInfoDataOutput]
type = "NatsOutput"
is_streaming = true   
subject = "hdim.rules.perbasisinfo_rules"
reconnect = true
message_matcher = "Logger == 'PerBasisInfoDataInput'"
encoder = "PayloadEncoder"
use_buffering = false
use_protocol = true 

[PerBasisInfoDataOutput.attr]

[PerBasisInfoDataOutput.buffering]
max_file_size = 1048576  #1MB
max_buffer_size = 10485760  #10MB
full_action = "drop"
cursor_update_count = 100


##################################PerCar   车辆列表csv##############################################
[PerCarDataInput]
type = "LogstreamerInput"
log_directory = "/opt/tools/PerCar"
file_match = '(?P<FileName>[^/]+).csv'
differentiator = ["FileName"]

[PerCarDataOutput]
type = "NatsOutput"
is_streaming = true   
subject = "hdim.rules.car_rules"
reconnect = true
message_matcher = "Logger == 'PerCarDataInput'"
encoder = "PayloadEncoder"
use_buffering = false
use_protocol = true 

[PerCarDataOutput.attr]

[PerCarDataOutput.buffering]
max_file_size = 1048576  #1MB
max_buffer_size = 10485760  #10MB
full_action = "drop"
cursor_update_count = 100

##################################PerLink   人员电话csv##############################################
[PerLinkDataInput]
type = "LogstreamerInput"
log_directory = "/opt/tools/PerLink"
file_match = '(?P<FileName>[^/]+).csv'
differentiator = ["FileName"]

[PerLinkDataOutput]
type = "NatsOutput"
is_streaming = true   
subject = "hdim.rules.phonenumber_rules"
reconnect = true
message_matcher = "Logger == 'PerLinkDataInput'"
encoder = "PayloadEncoder"
use_buffering = false
use_protocol = true 

[PerLinkDataOutput.attr]

[PerLinkDataOutput.buffering]
max_file_size = 1048576  #1MB
max_buffer_size = 10485760  #10MB
full_action = "drop"
cursor_update_count = 100


##################################RiskArea   重点地区csv##############################################
[RiskAreaDataInput]
type = "LogstreamerInput"
log_directory = "/opt/tools/RiskArea"
file_match = '(?P<FileName>[^/]+).csv'
differentiator = ["FileName"]

[RiskAreaDataOutput]
type = "NatsOutput"
is_streaming = true   
subject = "hdim.rules.riskarea_rules"
reconnect = true
message_matcher = "Logger == 'RiskAreaDataInput'"
encoder = "PayloadEncoder"
use_buffering = false
use_protocol = true 

[RiskAreaDataOutput.attr]

[RiskAreaDataOutput.buffering]
max_file_size = 1048576  #1MB
max_buffer_size = 10485760  #10MB
full_action = "drop"
cursor_update_count = 100

##################################Lable   重点地区csv##############################################
[LableDataInput]
type = "LogstreamerInput"
log_directory = "/opt/tools/Lable"
file_match = '(?P<FileName>[^/]+).csv'
differentiator = ["FileName"]

[LableDataOutput]
type = "NatsOutput"
is_streaming = true   
subject = "hdim.rules.label_rules"
reconnect = true
message_matcher = "Logger == 'LableDataInput'"
encoder = "PayloadEncoder"
use_buffering = false
use_protocol = true 

[LableDataOutput.attr]

[LableDataOutput.buffering]
max_file_size = 1048576  #1MB
max_buffer_size = 10485760  #10MB
full_action = "drop"
cursor_update_count = 100


